language: go

sudo: false

go:
  - 1.4.2
  - tip

before_install:
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v golang.org/x/tools/cmd/vet
  - go get -v github.com/golang/lint/golint
  - go get -v rsc.io/grind

install: go get -v -t ./...

script:
  - go test -v -cover ./...
  - gofmt -d .
  - go tool vet .
  - golint ./...
  - find . -iname "*.go" | xargs grind -v -diff
