language: go

sudo: false

go:
  - 1.6.3
  - tip

install: go get -v -d -t

script:
  - go test -v -cover -coverprofile=coverage.txt -covermode=atomic
  - >
    go get -v github.com/alecthomas/gometalinter &&
    gometalinter --install &&
    gometalinter -E gofmt -D gotype -D vetshadow -D dupl -D goconst -D interfacer -D gas --tests --deadline=10m

after_success:
  - bash <(curl -s https://codecov.io/bash)
